CREATE TABLE [dbo].[IGCUserGaf]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UserId] NVARCHAR(55) NOT NULL,
	[OperatorId] INT NOT NULL,
	[Gaf] NVARCHAR(MAX) NULL,
	[Created] DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [UQ_IGCUserGaf] UNIQUE NONCLUSTERED ([UserId]),
	CONSTRAINT [FK_IGCUserGaf_Operator] FOREIGN KEY ([OperatorId]) REFERENCES [dbo].[Operator] ([Id])
)
